# Generated by Django 4.2.8 on 2024-01-24 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('currency_exchange', '0001_initial'), ('currency_exchange', '0002_alter_currency_options_alter_provider_priority'), ('currency_exchange', '0003_alter_currency_code')]

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('code', models.CharField(max_length=3, unique=True)),
                ('symbol', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Currencies',
            },
        ),
        migrations.CreateModel(
            name='CurrencyExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('modification_datetime', models.DateTimeField(auto_now=True, null=True)),
                ('valuation_date', models.DateField(db_index=True)),
                ('rate_value', models.DecimalField(db_index=True, decimal_places=6, max_digits=18)),
                ('exchange_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='currency_exchange.currency')),
                ('source_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchanges', to='currency_exchange.currency')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('modification_datetime', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('priority', models.PositiveIntegerField(help_text='The lower the number, the higher the priority.', unique=True)),
                ('adapter_code', models.TextField(help_text='Python code to get the exchange rate.')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
